name: NextGen 2025 APP

on:
  push:
    branches:
      - main # Change to main if your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # You can specify the version you like

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build -- --prod --base-href "https://ciandt-brenodias.github.io/nextgen-2025-app/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/nextgen-2025-app
